# Generated by Django 5.2.8 on 2025-11-17 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_professor_campus_alter_professor_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='professor',
            name='campus',
            field=models.CharField(default='Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='departamento',
            field=models.CharField(default='A definir', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='MAT-TEMP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
