# Generated by Django 5.2.8 on 2025-11-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professor_data_cadastro_alter_professor_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='MAT-TEMP', max_length=20),
        ),
    ]
