# Generated by Django 5.2.8 on 2025-11-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_professor_campus_alter_professor_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oferecida', 'Aula Oferecida'), ('desejada', 'Aula Desejada')], default='oferecida', max_length=20)),
                ('disciplina', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('horario', models.CharField(help_text='Ex: 19:00-20:40', max_length=50)),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=20)),
                ('turma', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a aula')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('negociacao', 'Em Negociação'), ('realizada', 'Permuta Realizada')], default='disponivel', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professor')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
