# Generated by Django 5.2.8 on 2025-11-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='carga_horaria',
            field=models.CharField(choices=[('2h', '2 horas'), ('4h', '4 horas'), ('6h', '6 horas')], default='4h', max_length=10),
        ),
        migrations.AddField(
            model_name='aula',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], default='noturno', max_length=20),
        ),
    ]
