# Generated by Django 5.2.8 on 2025-11-17 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professor_data_cadastro_alter_professor_campus_and_more'),
        ('core', '0002_aula_carga_horaria_aula_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='turma',
        ),
        migrations.AlterField(
            model_name='aula',
            name='carga_horaria',
            field=models.IntegerField(help_text='Carga horária semanal em horas'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Língua Portuguesa'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biologia'), ('ingles', 'Inglês'), ('educacao_fisica', 'Educação Física'), ('artes', 'Artes'), ('filosofia', 'Filosofia'), ('sociologia', 'Sociologia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aula',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('permutada', 'Permutada')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('proposta', '📨 Nova Proposta'), ('aceita', '✅ Proposta Aceita'), ('recusada', '❌ Proposta Recusada'), ('cancelada', '🚫 Proposta Cancelada'), ('sistema', '🔔 Notificação do Sistema')], default='sistema', max_length=20)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='accounts.professor')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PropostaPermuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', '📋 Pendente'), ('aceita', '✅ Aceita'), ('recusada', '❌ Recusada'), ('cancelada', '🚫 Cancelada')], default='pendente', max_length=20)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem para o professor')),
                ('aula_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='core.aula')),
                ('aula_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_enviadas', to='core.aula')),
                ('professor_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='accounts.professor')),
                ('professor_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to='accounts.professor')),
            ],
            options={
                'verbose_name': 'Proposta de Permuta',
                'verbose_name_plural': 'Propostas de Permuta',
                'ordering': ['-data_proposta'],
            },
        ),
    ]
